### ISSUE TITLE
Trouble to try the samples in my S3 account

### ISSUE THREAD

**Issue by EUtrilla2002** [awslabs/aws-c-s3#331]
### Describe the issue

I'm trying to run the samples given ,however i don't know what i'm doing wrong by running this line of code.Previously I added my key and secret key as environment variable as  "AWS_ACCESS_KEY_ID" and"AWS_SECRET_ACCESS_KEY" .

I tried to run this command in the Ubuntu CLI

> aws-c-s3/build/samples/s3/s3 ls s3://pruebaxpn --region us-west-2

However,this error pops up:

> Failure while listing objects. Please check if you have valid credentials and s3 path is correct. Error: aws-c-s3: AWS_ERROR_S3_INVALID_RESPONSE_STATUS, Invalid response status from request

What I'm doing wrong? Thank you in advance

### Links

https://github.com/awslabs/aws-c-s3#readme

**Comment by yasminetalby** [comment]
Hello @EUtrilla2002 ,

Thank you very much for your submission. 
Could you check the following:
1. pruebaxpn is an existing bucket (no syntax error) and is located in region us-west-2
2. The credentials provided as environment variables are valid and not expired 
3. Potentially check if you have not set a different region as environment variable

Best regards,

Yasmine

**Comment by TingDaoK** [comment]
you can also do `aws-c-s3/build/samples/s3/s3 ls s3://pruebaxpn --region us-west-2 -v DEBUG` to get the debug level logs.

**Comment by EUtrilla2002** [comment]
Hello,thank you for answering
The bucket address,looking at the debug log,is correct.However something strange happens.
I created new credentials but it gets me this message :

![imagen](https://github.com/awslabs/aws-c-s3/assets/98873945/61d81071-59cf-4f5d-94aa-c00f83bd39ed)

It seems that the credentials are "expired" (i have created them 15 min ago and changed the enviromental values) and creates another ones?

The final error log is this one:

> [ERROR] [2023-07-12T09:56:01Z] [00007fad0c5ff640] [S3MetaRequest] - id=0x55dff92aac70 Meta request cannot recover from error 14343 (Invalid response status from request). (request=0x7fad04001150, response status=403)

This is my first time using S3 systems for an end-of-degree proyect so i'm a little lost here , help is much apreciated !

**Comment by yasminetalby** [comment]
Hello @EUtrilla2002 ,

Expired credentials are invalid so the behavior you are experiencing is expected. The request fails because of this hence the error message 
`[ERROR] [2023-07-12T09:56:01Z] [00007fad0c5ff640] [S3MetaRequest] - id=0x55dff92aac70 Meta request cannot recover from error 14343 (Invalid response status from request). (request=0x7fad04001150, response status=403)`.

How are you creating and setting up your environment credentials? I am assuming that you are following the[ IAM roles for Amazon EC2 documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html).
If you are using Assume Role. You can specify the maximum session duration for a role using the AWS Management Console or by using the AWS CLI or AWS API. When you use an AWS CLI or API operation to assume a role, you can specify a value for the DurationSeconds parameter. You can use this parameter to specify the duration of the role session, from 900 seconds (15 minutes) up to the maximum session duration setting for the role. ([See documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html#id_roles_use_view-role-max-session)).
[This blog post](https://repost.aws/knowledge-center/sts-iam-token-expired) is also a great resource to troubleshoot temporary security credential expiration using the AWS CLI.

If your use case is different could you please provide more detail regarding your credential set up steps?

Could you also please provide the full log around the error rather than a snippet? The log provided don't capture the error/logging leading to the error.

Thank you very much for your time and collaboration!
Best regards,

Yasmine

**Comment by EUtrilla2002** [comment]
Hi,sorry for the delay. It was a problem with the credentials :) i didn't put the administrator role

Thank you so much for the help!!!
